project:
  type: website
  output-dir: docs
  resources:
    - 2024.pdf

website:
  title: "Reports"
  image: assets/objective-3.png
  favicon: assets/wikihistories-logo.png
  site-url: https://wikihistories.github.io/reports
  twitter-card:
    creator: "@wikihistories"
    site: "@wikihistories"
  open-graph: true
  navbar:
    pinned: true
    tools:
      - icon: twitter
        href: https://twitter.com/wikihistories
      - icon: github
        menu:
          - text: Source Code
            url: https://github.com/wikihistories/reports
          - text: Report a Bug
            url: https://github.com/wikihistories/reports/issues
    left:
      - href: index.qmd
        text: Home
      - text: Reports
        menu:
        - href: 2023.qmd
          text: "2023 | How Australians are Represented in Wikipedia"
        - href: 2024.qmd
          text: "2024 | How Australian Places are Represented in Wikipedia"
      - href: LICENSE.md
        text: Copyright

format:
  html:
    theme:
      light: flatly
      dark: darkly
    css: styles.css
    toc: true

execute:
  freeze: auto


