project:
  type: website
  output-dir: docs

website:
  title: "Reports"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - text: Reports
        menu:
        - href: who-counts.qmd
          text: "2023 | Who Counts as Australian?"
format:
  html:
    theme:
      light: flatly
      dark: darkly
    css: styles.css
    toc: true



