---
title: "Reports"
---

This site hosts the annual Reports of the [wikihistories](https://wikihistories.net) project.

Each year, we will publish a report on a different aspect of Australian history in Wikipedia.

In 2023, we consider **people**. [Who Counts as Australian?](who-counts.html) uses a dataset of more than 80,000 Wikipedia biographies to reveal what kinds of people represent 'Australia' in the encyclopaedia.

In 2024, we consider **places**. `Where Counts as Australia?` will consider how the world's only continent-sized country makes its way into the world's only planet-sized encyclopaedia.

In 2025, we consider **events**. `When Counts as Australia?` will range over the 60,000-year human history of Australia, revealing which structures, conjunctures and events from emerge from deep time to take a place in the encyclopaedia.

These reports primarily fulfil Objectives 2 and 3 of the `wikihistories` project:

**Objective 2:** Map the scope of entries relating to Australian historic events on Wikipedia in order to analyse who and what is systematically omitted.

**Objective 3:** Investigate how Wikipedia’s representations are constructed through practice.

Supported by [Australian Research Council Grant DP220100662](https://dataportal.arc.gov.au/NCGP/Web/Grant/Grant/DP220100662).

