---
title: "How Australian places are represented in Wikipedia"
subtitle: "The Annual Report of the Wikihistories Project"
keywords:
  - Wikipedia
  - historiography
  - Australia
  - digital humanities
  - systemic bias
  - historical geography
date: July 2024
# doi: 
author:
  - name: Francesca Sidoti
    orcid: 0009-0005-1321-9372
    affiliation: University of Technology, Sydney
  - name: Michael Falk
    orcid: 0000-0001-9261-8390
    affiliation: University of Melbourne
    url: https://findanexpert.unimelb.edu.au/profile/1043380-michael-falk
  - name: Heather Ford
    orcid: 0000-0002-3500-9772
    affiliation: University of Technology, Sydney
    url: https://hblog.org/
  - name: Tamson Pietsch
    orcid: 0000-0002-8304-7108
    affiliation: University of Technology, Sydney
    url: https://capandgown.wordpress.com/
  - name: Tom Byers
    orcid: 0009-0005-9927-7679
    affiliation: University of Melbourne
    url: https://tom-byers.com
citation:
  type: report
  publisher: University of Technology, Sydney
  container-title: Reports of the Wikihistories Project
  number: 2
  pdf-url: which-places.pdf
google-scholar: true
bibliography: wikihistories.bib
format:
  html:
    description-meta: "How are Australian places represented in Wikipedia? In the second report of the wikihistories project, we explore the complex historical geography of Australia in the world's largest encyclopedia."
  pdf:
    header-includes: |
      \fancyfoot[LO,LE]{Reports of the Wikihistories Project, No. 2 (2024) doi:TBC}
---

```{r echo=FALSE}
file.path("scripts", "which-places-data.R") |> source()
```


## Frequently Asked Questions

### Which Australian places are most contentious?

```{r}
edit_threshold <- 50

figure_1_data <- edit_data |>
  dplyr::mutate(
    reverts = reverts$count,
    edits = edits$count,
    revert_ratio = reverts / edits
  ) |> 
  dplyr::filter(
    reverts + edits > edit_threshold
  ) |>
  dplyr::arrange(desc(revert_ratio)) |> 
  dplyr::slice_head(n=10) |> 
  tidyr::pivot_longer(
    cols=c(reverts, edits),
    values_to = "edits",
    names_to = "edit_type"
  ) |> 
  dplyr::select(title, revert_ratio, edit_type, edits) |> 
  dplyr::mutate(
    title = forcats::fct_inorder(title) |> forcats::fct_rev() # To preserve order in chart
  )
figure_1_data |> ggplot2::ggplot(
    ggplot2::aes(y = title, x = edits, fill = edit_type),
    width = 10,
    height = 5
  ) +
  ggplot2::geom_col() +
  ggplot2::labs(
    title = "10 Most Contentious Articles",
    subtitle = glue::glue("Ranked by reverted edits / human edits, on articles with more than {edit_threshold} edits"),
    x = "Human + Reverted edits",
    y = "Place name",
    fill = "Edit type"
  )
```



### Which language edition has the most Australian places?

```{r}
language_data <- places |> 
  dplyr::select(sitelinks) |> 
  tidyr::unnest(sitelinks) |> 
  dplyr::group_by(sitelinks) |> 
  dplyr::summarise(n = n()) |> 
  dplyr::rename(wiki_code = sitelinks) |> 
  dplyr::arrange(desc(n)) |> 
  dplyr::mutate(
    lang_code = stringr::str_remove(wiki_code, "wiki")
  ) |> 
  dplyr::left_join(
    lang_codes,
    by = dplyr::join_by(lang_code == code)
  ) |> 
  dplyr::rename(language_edition = name) |> 
  dplyr::mutate(
    language_edition = forcats::fct_inorder(language_edition)
  ) |> 
  tidyr::drop_na()
language_data |> 
  dplyr::slice_head(n=15) |> 
  ggplot2::ggplot(
    ggplot2::aes(x = language_edition, y = n)
  ) +
  ggplot2::geom_col() +
  ggplot2::labs(
    title = "Lsjbot has written most of the Australian place articles",
    subtitle = "Cebunao and Swedish Wikipedias are largely bot-written",
    x = "Language Edition",
    y = "Number of Articles for Australian Places"
  ) +
  ggplot2::theme(
    axis.text.x = ggplot2::element_text(angle = 90)
  )
```


### Which are the ignored places?

```{r}
edit_data |> 
  dplyr::group_by(instance_of) |> 
  dplyr::summarise(edits = sum(edits$count + reverts$count + bots$count)) |> 
  dplyr::arrange(desc(edits)) |> 
  dplyr::left_join(types, dplyr::join_by(instance_of == type)) |> 
  dplyr::filter(on_english_wikipedia) |> 
  # Weirdly, if you sort in 'descending' order, then the groups
  # will be arranged in ascending order on the plot...
  # Discrete scales in ggplot2 are a bit weird.
  dplyr::slice_head(n = 10) |> 
  dplyr::mutate(
    label = stringr::str_to_title(label),
    # Correctly order categories in plot
    label = forcats::fct_inorder(label)
  ) |> 
  ggplot2::ggplot(
    ggplot2::aes(x = edits, y = label)
  ) +
  ggplot2::geom_col() +
  ggplot2::scale_y_discrete() +
  ggplot2::labs(
    x = "Total edits for all pages in category",
    y = "Place type"
  )
```


### Who reads the articles about Australian places?

```{r}
pageview_data |> 
  # dplyr::filter(country_name != "Australia") |> 
  dplyr::mutate(
    country_name = dplyr::case_when(
      country_name == "United States" ~ "USA",
      country_name == "United Kingdom" ~ "UK",
      .default = as.character(country_name)
    )
  ) |> 
  dplyr::group_by(country_name) |> 
  dplyr::summarise(pageviews = sum(pageviews)) |> 
  dplyr::full_join(
    ggplot2::map_data("world2"),
    by = dplyr::join_by(country_name == region)) |> 
  ggplot2::ggplot(
    ggplot2::aes(fill = pageviews, group = group, x = long, y = lat)
    ) +
  ggplot2::geom_polygon() +
  ggplot2::labs(
    x = "Latitude",
    y = "Longitude",
    fill = "Pageviews",
    title = "Pageviews of Australian place articles by country",
    subtitle = glue::glue("From {attr(pageview_data, 'from') |> format('%eth %B %Y')} to {attr(pageview_data, 'to') |> format('%eth %B %Y')}")
    ) +
  ggplot2::scale_fill_continuous(labels = scales::label_comma(big.mark = " "))
```



### Which Australian places exist?
